#!/usr/bin/env node
/**
 * Copies the two stylesheets the static render inlines — src/shell/theme.css
 * (the tokens) and src/shell/document.css (the document) — into generated
 * TypeScript modules, verbatim, for the DOM-free render entry, which cannot
 * load a stylesheet and whose tests run where a CSS import resolves to
 * nothing. `--check` fails when a copy is stale; `pnpm build` runs it first.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");

const SHEETS = [
	{
		source: "src/shell/theme.css",
		out: "src/shell/theme.generated.ts",
		name: "THEME_CSS",
		doc: "The token sheet, verbatim, for a render with no DOM to link it into.",
	},
	{
		source: "src/shell/document.css",
		out: "src/shell/document.generated.ts",
		name: "DOCUMENT_CSS",
		doc: "The document sheet, verbatim: the same rules the editor reads.",
	},
];

function generated({ source, name, doc }) {
	const css = readFileSync(join(root, source), "utf8");
	// A template literal, not JSON: the formatter leaves its contents alone,
	// so the check compares like with like.
	const escaped = css
		.replace(/\\/g, "\\\\")
		.replace(/`/g, "\\`")
		.replace(/\$\{/g, "\\${");
	return `// Generated by scripts/tokens/emit-css.mjs from ${source}. Do not edit.
/** ${doc} */
export const ${name} = \`${escaped}\`;
`;
}

const check = process.argv.includes("--check");
let stale = false;
for (const sheet of SHEETS) {
	const file = generated(sheet);
	const out = join(root, sheet.out);
	if (check) {
		let current = "";
		try {
			current = readFileSync(out, "utf8");
		} catch {}
		if (current !== file) {
			console.error(`${sheet.out} is stale; run: pnpm run tokens`);
			stale = true;
		}
	} else {
		writeFileSync(out, file);
		console.log(`wrote ${out}`);
	}
}
if (stale) process.exit(1);
