#!/usr/bin/env node
/**
 * Copies src/shell/theme.css into src/shell/theme.generated.ts, verbatim, for
 * the DOM-free render entry, which cannot load a stylesheet and whose tests
 * run where a CSS import resolves to nothing. `--check` fails when the copy
 * is stale; `pnpm build` runs it first.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const source = join(root, "src/shell/theme.css");
const out = join(root, "src/shell/theme.generated.ts");
const css = readFileSync(source, "utf8");
// A template literal, not JSON: the formatter leaves its contents alone, so
// the check compares like with like.
const escaped = css
	.replace(/\\/g, "\\\\")
	.replace(/`/g, "\\`")
	.replace(/\$\{/g, "\\${");
const file = `// Generated by scripts/tokens/emit-theme.mjs from src/shell/theme.css. Do not edit.
/** The token sheet, verbatim, for a render with no DOM to link it into. */
export const THEME_CSS = \`${escaped}\`;
`;
if (process.argv.includes("--check")) {
	let current = "";
	try {
		current = readFileSync(out, "utf8");
	} catch {}
	if (current !== file) {
		console.error(
			"src/shell/theme.generated.ts is stale; run: pnpm run tokens",
		);
		process.exit(1);
	}
} else {
	writeFileSync(out, file);
	console.log(`wrote ${out}`);
}
