// Generated by scripts/generate-render-tokens.mjs from src/shell/theme.css.
// Do not edit: run `pnpm run tokens` after changing the theme.

/** The palette a static render carries, so it needs no stylesheet of ours. */
export const ATELIER_RENDER_TOKENS = `.atelier-render {
	--atelier-ink: rgb(28, 25, 23);
	--atelier-ink-muted: rgb(68, 64, 60);
	--atelier-ink-subtle: rgb(120, 113, 108);
	--atelier-bg: rgb(255, 255, 255);
	--atelier-bg-muted: rgb(250, 250, 249);
	--atelier-border: rgb(236, 232, 226);
	--atelier-border-subtle: rgb(244, 241, 236);
	--atelier-accent: rgb(234, 88, 12);
	--atelier-action: rgb(194, 65, 12);
	--atelier-added-bg: rgb(237, 250, 242);
	--atelier-added-ink: rgb(22, 101, 52);
	--atelier-added-edge: rgb(21, 128, 61);
	--atelier-removed-bg: rgb(254, 242, 242);
	--atelier-removed-ink: rgb(153, 27, 27);
	--atelier-removed-edge: rgb(185, 28, 28);
	--atelier-modified-bg: rgb(251, 239, 228);
	--atelier-moved-edge: rgb(68, 112, 157);
	--atelier-font-sans: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif;
	--atelier-font-mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
	--atelier-radius: 8px;
	--atelier-radius-small: 4px;
}`;
