// Generated by scripts/tokens/emit-css.mjs from src/shell/theme.css. Do not edit.
/** The token sheet, compacted, for a render with no DOM to link it into. */
export const THEME_CSS = `:root,
:host {
color-scheme: light;
--atelier-bg: light-dark(
rgb(244 242 239),
rgb(22 20 18)
);
--atelier-panel: light-dark(
rgb(255 255 255),
rgb(28 25 23)
);
--atelier-bg-subtle: light-dark(
rgb(250 250 249),
rgb(35 31 28)
);
--atelier-bg-hover: light-dark(
rgb(245 242 237),
rgb(41 37 34)
);
--atelier-bg-hover-strong: light-dark(
rgb(236 231 223),
rgb(52 47 42)
);
--atelier-bg-active: light-dark(
rgb(233 231 225),
rgb(58 53 47)
);
--atelier-bg-selection: light-dark(
rgb(224 216 207),
rgb(74 62 50)
);
--atelier-highlight: light-dark(
rgb(254 240 138),
rgb(113 63 18)
);
--atelier-scrollbar: light-dark(
rgb(120 113 108 / 0.6),
rgb(140 133 124 / 0.6)
);
--atelier-fg: light-dark(
rgb(28 25 23),
rgb(245 242 237)
);
--atelier-fg-muted: light-dark(
rgb(68 64 60),
rgb(190 183 175)
);
--atelier-fg-subtle: light-dark(
rgb(120 113 108),
rgb(140 133 124)
);
--atelier-fg-faint: light-dark(
rgb(168 162 158),
rgb(100 94 88)
);
--atelier-border: light-dark(
rgb(236 232 226),
rgb(54 49 45)
);
--atelier-border-subtle: light-dark(
rgb(244 241 236),
rgb(41 37 34)
);
--atelier-border-strong: light-dark(
rgb(214 211 209),
rgb(87 83 78)
);
--atelier-ring: var(--atelier-accent);
--atelier-accent: light-dark(
rgb(194 65 12),
rgb(251 146 60)
);
--atelier-accent-hover: light-dark(rgb(154 52 18), rgb(253 186 116));
--atelier-accent-on: light-dark(
rgb(255 255 255),
rgb(28 25 23)
);
--atelier-accent-subtle: light-dark(
rgb(251 239 228),
rgb(58 38 24)
);
--atelier-accent-border: light-dark(
rgb(243 216 190),
rgb(120 66 30)
);
--atelier-link: light-dark(
rgb(234 88 12),
rgb(253 186 116)
);
--atelier-link-hover: var(--atelier-accent);
--atelier-accent-gradient: linear-gradient(
180deg,
rgb(249 115 22) 0%,
rgb(234 88 12) 100%
);
--atelier-shadow-accent:
0 4px 16px rgb(232 89 12 / 0.38), inset 0 1px 0 rgb(255 255 255 / 0.25);
--atelier-danger: light-dark(
rgb(220 38 38),
rgb(248 113 113)
);
--atelier-danger-subtle: light-dark(rgb(254 242 242), rgb(59 18 18));
--atelier-danger-border: light-dark(rgb(185 28 28), rgb(153 27 27));
--atelier-success: light-dark(rgb(22 163 74), rgb(74 222 128));
--atelier-success-subtle: light-dark(rgb(240 253 244), rgb(18 48 28));
--atelier-success-border: light-dark(rgb(21 128 61), rgb(22 101 52));
--atelier-warning: light-dark(rgb(161 98 7), rgb(250 204 21));
--atelier-warning-subtle: light-dark(rgb(254 252 232), rgb(48 42 8));
--atelier-warning-border: light-dark(rgb(254 240 138), rgb(133 77 14));
--atelier-diff-added: light-dark(
rgb(22 101 52),
rgb(134 239 172)
);
--atelier-diff-added-subtle: light-dark(
rgb(34 197 94 / 0.08),
rgb(34 197 94 / 0.16)
);
--atelier-diff-removed: light-dark(rgb(153 27 27), rgb(252 165 165));
--atelier-diff-removed-subtle: light-dark(
rgb(239 68 68 / 0.07),
rgb(239 68 68 / 0.16)
);
--atelier-diff-modified: light-dark(
rgb(194 65 12),
rgb(253 186 116)
);
--atelier-diff-modified-subtle: light-dark(
rgb(249 115 22 / 0.1),
rgb(249 115 22 / 0.16)
);
--atelier-diff-moved: light-dark(rgb(68 112 157), rgb(125 170 220));
--atelier-diff-conflict: light-dark(rgb(125 78 158), rgb(180 140 210));
--atelier-overlay: rgb(28 25 23);
--atelier-overlay-raised: rgb(42 38 32);
--atelier-overlay-hover: rgb(58 53 47);
--atelier-overlay-hairline: rgb(
255 255 255 / 0.09
);
--atelier-overlay-hairline-strong: rgb(255 255 255 / 0.16);
--atelier-overlay-border: rgb(58 53 47);
--atelier-overlay-border-strong: rgb(87 83 78);
--atelier-overlay-fg: rgb(231 226 218);
--atelier-overlay-fg-muted: rgb(201 194 184);
--atelier-overlay-fg-subtle: rgb(140 133 124);
--atelier-overlay-accent: rgb(232 168 124);
--atelier-overlay-danger: rgb(235 165 156);
--atelier-overlay-danger-border: rgb(90 58 58);
--atelier-overlay-success: rgb(167 217 180);
--atelier-overlay-diff-added: rgb(134 239 172);
--atelier-overlay-diff-modified: rgb(253 186 116);
--atelier-overlay-diff-removed: rgb(252 165 165);
--atelier-overlay-diff-moved: rgb(125 170 220);
--atelier-overlay-diff-conflict: rgb(180 140 210);
--atelier-scrim: rgb(20 16 10 / 0.55);
--atelier-shadow-overlay: 0 14px 32px rgb(28 25 23 / 0.42);
--atelier-syntax-keyword: light-dark(
oklch(0.5 0.14 245),
oklch(0.78 0.12 245)
);
--atelier-syntax-string: light-dark(
oklch(0.49 0.11 155),
oklch(0.8 0.13 155)
);
--atelier-syntax-number: light-dark(
oklch(0.52 0.13 55),
oklch(0.82 0.13 70)
);
--atelier-syntax-constant: light-dark(
oklch(0.5 0.14 300),
oklch(0.78 0.12 300)
);
--atelier-syntax-comment: var(
--atelier-fg-subtle
);
--atelier-syntax-type: var(
--atelier-fg
);
--atelier-syntax-property: var(--atelier-fg-muted);
--atelier-syntax-invalid: var(--atelier-danger-border);
--atelier-tag-gray: light-dark(#e9e7e4, #3a3633);
--atelier-tag-gray-fg: light-dark(#44403c, #d6d3d1);
--atelier-tag-brown: light-dark(#eee3da, #4a382c);
--atelier-tag-brown-fg: light-dark(#60432e, #e3c9b5);
--atelier-tag-orange: light-dark(#fae8d4, #5a3a1c);
--atelier-tag-orange-fg: light-dark(#783d10, #f6c9a0);
--atelier-tag-yellow: light-dark(#f6efc9, #4d4410);
--atelier-tag-yellow-fg: light-dark(#604900, #efe2a0);
--atelier-tag-green: light-dark(#dfece3, #22402c);
--atelier-tag-green-fg: light-dark(#285238, #b7dcc4);
--atelier-tag-blue: light-dark(#deebf7, #203a52);
--atelier-tag-blue-fg: light-dark(#294d69, #b6d3ea);
--atelier-tag-purple: light-dark(#ebe2f3, #3d2c4e);
--atelier-tag-purple-fg: light-dark(#583c70, #d3c2e6);
--atelier-tag-pink: light-dark(#f5e0ec, #4e2c40);
--atelier-tag-pink-fg: light-dark(#693b53, #e6c3d7);
--atelier-tag-red: light-dark(#f8e0de, #4f2a28);
--atelier-tag-red-fg: light-dark(#7b332f, #efbfba);
--atelier-folder: light-dark(
rgb(96 165 250),
rgb(125 180 255)
);
--atelier-panel-header-height: 40px;
--atelier-radius-tag: 3px;
--atelier-radius-control: 7px;
--atelier-radius-panel: 8px;
--atelier-radius-full: 9999px;
--atelier-space-1: 4px;
--atelier-space-2: 8px;
--atelier-space-3: 12px;
--atelier-space-4: 16px;
--atelier-space-5: 24px;
--atelier-space-6: 32px;
--atelier-text-ui-xs: 11px;
--atelier-text-ui-xs-lh: 16px;
--atelier-text-ui-sm: 11.5px;
--atelier-text-ui-sm-lh: 16px;
--atelier-text-ui-md: 12.5px;
--atelier-text-ui-md-lh: 16px;
--atelier-text-ui-lg: 13px;
--atelier-text-ui-lg-lh: 20px;
--atelier-font-sans:
ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji",
"Segoe UI Symbol", "Noto Color Emoji";
--atelier-font-mono:
ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace;
--atelier-shadow-sm: 0 1px 2px rgb(28 25 23 / 0.05);
--atelier-shadow-md:
0 4px 16px -2px rgb(0 0 0 / 0.08), 0 2px 4px -1px rgb(0 0 0 / 0.08);
--atelier-shadow-lg:
0 12px 32px -4px rgb(0 0 0 / 0.08), 0 4px 8px -2px rgb(0 0 0 / 0.08);
--atelier-duration-fast: 100ms;
--atelier-duration: 120ms;
--atelier-duration-slow: 160ms;
}`;
